{
 "title": "AS112 KnotDNS Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "AS112 Node:",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n   bucket: \"AS112\",\n   measurement: \"stats\",\n   tag: \"host\"\n)\n"
   }
  ]
 },
 "panels": [
  { "title": "Data / Avg Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Usage by Function",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r.bytes != \"\" and r.bytes != \"other\" and r.bytes != \"transfer\")\n  |> map(fn: (r) => ({ r with bytes: strings.toUpper(v: r.bytes) }))\n  |> group(columns: [\"host\", \"bytes\"])\n  |> spread()\n  |> group(columns: [\"bytes\"])\n  |> sum()\n  |> group()\n  |> top(n: 4)\n  \n"
    }
   ]
  },
  {
   "title": "Average System Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname:regex}$/)\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> group(columns: [\"cpu\"])\n  |> mean()\n  |> group()\n  |> mean()"
    }
   ]
  },
  {
   "title": "Stats Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Total Received Requests by Request Type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname:regex}$/)\n  |> spread()\n  |> group(columns: [\"operation\"])\n  |> sum()\n  |> group()\n  |> map(fn: (r) => ({\n      r with\n      operation: strings.toUpper(v: r.operation)\n    }))\n  |> top(n: 6, columns: [\"_value\"])\n"
    }
   ]
  },
  {
   "title": "Total Received Requests by Query Type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"query-type\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => \n        r[\"type\"] == \"A\" or \n        r[\"type\"] == \"AAAA\" or \n        r[\"type\"] == \"ANY\" or \n        r[\"type\"] == \"CNAME\" or \n        r[\"type\"] == \"HTTPS\" or \n        r[\"type\"] == \"MX\" or \n        r[\"type\"] == \"NS\" or \n        r[\"type\"] == \"PTR\" or \n        r[\"type\"] == \"SOA\" or \n        r[\"type\"] == \"SPF\" or \n        r[\"type\"] == \"TXT\"\n    )\n  |> spread()\n  |> group(columns: [\"type\"])\n  |> sum()\n  |> group()\n  |> top(n: 6, columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Total Received Requests by Protocol",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"request-protocol\")\n  |> filter(fn: (r) => r[\"host\"] =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r[\"protocol\"] =~ /^.*[4,6]$/)\n  |> spread()\n  |> group(columns: [\"protocol\"])\n  |> sum()\n  |> group()\n  |> map(fn: (r) => ({\n    r with\n    protocol: strings.toUpper(v: r.protocol)\n  }))\n  |> top(n: 6, columns: [\"_value\"])"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "UDP4 Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"request-protocol\")\n  |> filter(fn: (r) => r[\"protocol\"] == \"udp4\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  // Aggregate using last to get the value difference within each 1-minute window for all hosts\n  |> aggregateWindow(every: 1m, fn: spread, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "UDP6 Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"request-protocol\")\n  |> filter(fn: (r) => r[\"protocol\"] == \"udp6\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  // Aggregate using last to get the final value within each 1-minute window for all hosts\n  |> aggregateWindow(every: 1m, fn: spread, createEmpty: false)"
    }
   ]
  },
  {
   "title": "TCP4 Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"request-protocol\")\n  |> filter(fn: (r) => r[\"protocol\"] == \"tcp4\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  // Aggregate using last to get the final value within each 1-minute window for all hosts\n  |> aggregateWindow(every: 1m, fn: spread, createEmpty: false)"
    }
   ]
  },
  {
   "title": "TCP6 Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"request-protocol\")\n  |> filter(fn: (r) => r[\"protocol\"] == \"tcp6\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  // Aggregate using last to get the final value within each 1-minute window for all hosts\n  |> aggregateWindow(every: 1m, fn: spread, createEmpty: false)"
    }
   ]
  }
 ]
}