{
 "title": "Resource Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n   bucket: \"AS112\",\n   measurement: \"stats\",\n   tag: \"host\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queries Per Second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> group(columns: [\"host\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"])\n  |> mean()\n  |> group() // Remove grouping to prepare for ranking across all hosts\n  |> sort(columns: [\"_value\"], desc: true) // Sort by averaged QPS in descending order\n  |> limit(n: 5) // Select the top 5 hosts\n"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  |> group(columns: [\"host\"])\n  // Calculate the derivative to find the rate of change (queries per second)\n  |> derivative(unit: 1s, nonNegative: true)\n  // Optionally, you might still want to aggregate over a window to smooth out spikes\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\")\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> sort(columns: [\"_value\"], desc: true) // Sort hosts by their average value in descending order\n  |> top(n: 5, columns: [\"_value\"])\n  |> mean()\n  |> yield(name: \"CPU\")\n  |> group()\n  |> top(n: 5, columns: [\"_value\"])\n"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "CPU Usage Avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n\n  |> sort(columns: [\"_value\"], desc: true) // Sort hosts by their average value in descending order\n  |> top(n: 5, columns: [\"_value\"])\n  |> mean()\n  |> group()\n  |> top(n: 5, columns: [\"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "System CPU Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Active Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n\n  |> sort(columns: [\"_value\"], desc: true) // Sort hosts by their average value in descending order\n  |> top(n: 5, columns: [\"_value\"])\n  |> mean()\n  |> yield(name: \"Memory\")\n  |> group()\n  |> top(n: 5, columns: [\"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "Active Memory Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"device\"] == \"sda1\" or r[\"device\"] == \"sda15\")\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n\n  |> sort(columns: [\"_value\"], desc: true) // Sort hosts by their average value in descending order\n  |> top(n: 5, columns: [\"_value\"])\n  |> mean()\n  |> yield(name: \"usage\")\n  |> group()\n  |> top(n: 5, columns: [\"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "Disk Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"device\"] == \"sda1\" or r[\"device\"] == \"sda15\")\n  |> filter(fn: (r) => r[\"host\"]=~ /^${hostname:regex}$/)\n\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}