{
 "title": "Regional QPS",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "North America", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-chi\" or \n    r[\"host\"] == \"as112-den\" or \n    r[\"host\"] == \"as112-dfw\" or \n    r[\"host\"] == \"as112-iad\" or \n    r[\"host\"] == \"as112-lax\" or \n    r[\"host\"] == \"as112-lga\" or \n    r[\"host\"] == \"as112-mci\" or \n    r[\"host\"] == \"as112-mia\" or \n    r[\"host\"] == \"as112-phx\" or \n    r[\"host\"] == \"as112-rdu\" or \n    r[\"host\"] == \"as112-sea\" or \n    r[\"host\"] == \"as112-sjc\" or \n    r[\"host\"] == \"as112-yul\" or \n    r[\"host\"] == \"as112-tor\"\n  )\n  |> group(columns: [\"host\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"])\n  |> mean()\n  |> group() // Remove grouping to prepare for ranking across all hosts\n  |> sort(columns: [\"_value\"], desc: true) // Sort by averaged QPS in descending order\n"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n    |> filter(fn: (r) => \n    r[\"host\"] == \"as112-chi\" or \n    r[\"host\"] == \"as112-den\" or \n    r[\"host\"] == \"as112-dfw\" or \n    r[\"host\"] == \"as112-iad\" or \n    r[\"host\"] == \"as112-lax\" or \n    r[\"host\"] == \"as112-lga\" or \n    r[\"host\"] == \"as112-mci\" or \n    r[\"host\"] == \"as112-mia\" or \n    r[\"host\"] == \"as112-phx\" or \n    r[\"host\"] == \"as112-rdu\" or \n    r[\"host\"] == \"as112-sea\" or \n    r[\"host\"] == \"as112-sjc\" or \n    r[\"host\"] == \"as112-yul\" or \n    r[\"host\"] == \"as112-tor\"\n  )\n  |> group(columns: [\"host\"])\n  // Calculate the derivative to find the rate of change (queries per second)\n  |> derivative(unit: 1s, nonNegative: true)\n  // Optionally, you might still want to aggregate over a window to smooth out spikes\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"bytes\"] == \"other\" or r[\"bytes\"] == \"reply\" or r[\"bytes\"] == \"query\" or r[\"bytes\"] == \"transfer\" or r[\"bytes\"] == \"update\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-chi\" or \n    r[\"host\"] == \"as112-den\" or \n    r[\"host\"] == \"as112-dfw\" or \n    r[\"host\"] == \"as112-iad\" or \n    r[\"host\"] == \"as112-lax\" or \n    r[\"host\"] == \"as112-lga\" or \n    r[\"host\"] == \"as112-mci\" or \n    r[\"host\"] == \"as112-mia\" or \n    r[\"host\"] == \"as112-phx\" or \n    r[\"host\"] == \"as112-rdu\" or \n    r[\"host\"] == \"as112-sea\" or \n    r[\"host\"] == \"as112-sjc\" or \n    r[\"host\"] == \"as112-yul\" or \n    r[\"host\"] == \"as112-tor\"\n  )\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n  |> spread()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)  \n"
    }
   ]
  },
  { "title": "South America", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Avg QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-gru\" or \n    r[\"host\"] == \"as112-scl\"\n)\n\n  |> group(columns: [\"host\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"])\n  |> mean()\n  |> group() // Remove grouping to prepare for ranking across all hosts\n  |> sort(columns: [\"_value\"], desc: true) // Sort by averaged QPS in descending order\n"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-gru\" or \n    r[\"host\"] == \"as112-scl\"\n)\n\n  |> group(columns: [\"host\"])\n  // Calculate the derivative to find the rate of change (queries per second)\n  |> derivative(unit: 1s, nonNegative: true)\n  // Optionally, you might still want to aggregate over a window to smooth out spikes\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"bytes\"] == \"other\" or r[\"bytes\"] == \"reply\" or r[\"bytes\"] == \"query\" or r[\"bytes\"] == \"transfer\" or r[\"bytes\"] == \"update\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-gru\" or \n    r[\"host\"] == \"as112-scl\"\n)\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n  |> spread()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)  \n"
    }
   ]
  },
  { "title": "Europe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Avg QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-ams\" or \n    r[\"host\"] == \"as112-cdg\" or \n    r[\"host\"] == \"as112-fra\" or \n    r[\"host\"] == \"as112-lhr\" or \n    r[\"host\"] == \"as112-mad\" or \n    r[\"host\"] == \"as112-man\" or \n    r[\"host\"] == \"as112-otp\" or \n    r[\"host\"] == \"as112-waw\"\n)\n\n\n  |> group(columns: [\"host\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"])\n  |> mean()\n  |> group() // Remove grouping to prepare for ranking across all hosts\n  |> sort(columns: [\"_value\"], desc: true) // Sort by averaged QPS in descending order\n"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-ams\" or \n    r[\"host\"] == \"as112-cdg\" or \n    r[\"host\"] == \"as112-fra\" or \n    r[\"host\"] == \"as112-lhr\" or \n    r[\"host\"] == \"as112-mad\" or \n    r[\"host\"] == \"as112-man\" or \n    r[\"host\"] == \"as112-otp\" or \n    r[\"host\"] == \"as112-waw\"\n)\n\n\n  |> group(columns: [\"host\"])\n  // Calculate the derivative to find the rate of change (queries per second)\n  |> derivative(unit: 1s, nonNegative: true)\n  // Optionally, you might still want to aggregate over a window to smooth out spikes\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"bytes\"] == \"other\" or r[\"bytes\"] == \"reply\" or r[\"bytes\"] == \"query\" or r[\"bytes\"] == \"transfer\" or r[\"bytes\"] == \"update\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-ams\" or \n    r[\"host\"] == \"as112-cdg\" or \n    r[\"host\"] == \"as112-fra\" or \n    r[\"host\"] == \"as112-lhr\" or \n    r[\"host\"] == \"as112-mad\" or \n    r[\"host\"] == \"as112-man\" or \n    r[\"host\"] == \"as112-otp\" or \n    r[\"host\"] == \"as112-waw\"\n)\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n  |> spread()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)  \n"
    }
   ]
  },
  { "title": "APAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Avg QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-acc\" or \n    r[\"host\"] == \"as112-bom\" or \n    r[\"host\"] == \"as112-dxb\" or \n    r[\"host\"] == \"as112-hkg\" or \n    r[\"host\"] == \"as112-jnb\" or \n    r[\"host\"] == \"as112-maa\" or \n    r[\"host\"] == \"as112-nbo\" or \n    r[\"host\"] == \"as112-sin\" or \n    r[\"host\"] == \"as112-syd\" or \n    r[\"host\"] == \"as112-tyo\"\n)\n\n\n\n  |> group(columns: [\"host\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"])\n  |> mean()\n  |> group() // Remove grouping to prepare for ranking across all hosts\n  |> sort(columns: [\"_value\"], desc: true) // Sort by averaged QPS in descending order\n"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"server-operation\")\n  |> filter(fn: (r) => r[\"operation\"] == \"query\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-acc\" or \n    r[\"host\"] == \"as112-bom\" or \n    r[\"host\"] == \"as112-dxb\" or \n    r[\"host\"] == \"as112-hkg\" or \n    r[\"host\"] == \"as112-jnb\" or \n    r[\"host\"] == \"as112-maa\" or \n    r[\"host\"] == \"as112-nbo\" or \n    r[\"host\"] == \"as112-sin\" or \n    r[\"host\"] == \"as112-syd\" or \n    r[\"host\"] == \"as112-tyo\"\n)\n\n\n\n  |> group(columns: [\"host\"])\n  // Calculate the derivative to find the rate of change (queries per second)\n  |> derivative(unit: 1s, nonNegative: true)\n  // Optionally, you might still want to aggregate over a window to smooth out spikes\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AS112\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"bytes\"] == \"other\" or r[\"bytes\"] == \"reply\" or r[\"bytes\"] == \"query\" or r[\"bytes\"] == \"transfer\" or r[\"bytes\"] == \"update\")\n  |> filter(fn: (r) => \n    r[\"host\"] == \"as112-acc\" or \n    r[\"host\"] == \"as112-bom\" or \n    r[\"host\"] == \"as112-dxb\" or \n    r[\"host\"] == \"as112-hkg\" or \n    r[\"host\"] == \"as112-jnb\" or \n    r[\"host\"] == \"as112-maa\" or \n    r[\"host\"] == \"as112-nbo\" or \n    r[\"host\"] == \"as112-sin\" or \n    r[\"host\"] == \"as112-syd\" or \n    r[\"host\"] == \"as112-tyo\"\n)\n\n\n  |> group(columns: [\"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n  |> spread()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)  \n"
    }
   ]
  }
 ]
}